MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224_ep300
  DROP_PATH_RATE: 0.2
  DROP_RATE: 0
  #PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window10_320_ep150.pth"
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 2, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7 

    PATCH_SIZE: 4
    IN_CHANS: 3
    MLP_RATIO: 4.
    QKV_BIAS: True
    QK_SCALE: None
    APE: False
    PATCH_NORM: True


DATASETS:
  Synapse:
    NUM_CLASSES: 9
    ROOT_PATH: "./data/project_TransUNet/data/Synapse"
    LIST_DIR: "./lists/lists_Synapse"
    Z_SPACING: 1

DATA:
  IMG_SIZE: 224

TRAIN:
  OUTPUT_DIR: "output\\swin_tiny_patch4_window7_224_ep300"
  MAX_EPOCHS: 300
  BASE_LR: 0.05
  BATCH_SIZE: 24

  DETERMINISTIC: True
  SEED: 1234
  N_GPU: 1
  USE_CHECKPOINT: False

TEST:
  OUTPUT_DIR: "test_log\\swin_tiny_patch4_window7_224_ep300"
  LOG_OUTPUT_DIR: "test_log\\swin_tiny_patch4_window7_224_ep300\\log"

  DETERMINISTIC: True
  SEED: 1234
  N_GPU: 1
  IS_SAVENII: True